cc_library(
    name = "buffer_base",
    srcs = [
        "buffer.cc",    
    ],
    hdrs = [
        "buffer.h",
    ],
)

cc_library(
    name = "buffer",
    srcs = [
        "buffer.cc",
#        "vector_buffer.cc",
        "wrapped_buffer.cc",
    ],
    hdrs = [
        "buffer.h",
#        "vector_buffer.h",
        "wrapped_buffer.h",
    ],
)
